import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowRight, faCarSide, faCheck, faCirclePlay, faClock, faGem, faHeadset, faLandmark, faMosque, faPlaneDeparture, faRoad, faRoute, faShieldHalved, faStar, faSuitcaseRolling } from "@fortawesome/free-solid-svg-icons";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import { Link } from "wouter";
import { media, reels, services, tickerItems, type Service, type Vehicle } from "@/data/siteData";
import { openBooking } from "@/components/booking/BookingModal";

const iconMap: Record<string, IconDefinition> = { plane: faPlaneDeparture, mosque: faMosque, landmark: faLandmark, route: faRoute, road: faRoad, star: faStar };

export function Hero() {
  return <section className="hero-section">
    <div className="hero-backdrop" />
    <div className="hero-content container"><div className="hero-copy"><span className="eyebrow eyebrow--gold">Saudi journeys, considered</span><h1>Move with <em>intention.</em><br />Arrive with ease.</h1><p>Premium transportation for airport transfers, Makkah, Madinah, Ziyarat journeys, and the moments in between.</p><div className="hero-actions"><Link className="gold-button" href="/services">Explore services <FontAwesomeIcon icon={faArrowRight} /></Link><button className="text-link text-link--light" onClick={openBooking}>Book a ride <FontAwesomeIcon icon={faArrowRight} /></button></div><div className="hero-proof"><span><FontAwesomeIcon icon={faShieldHalved} /> Safety-led</span><span><FontAwesomeIcon icon={faClock} /> Clear coordination</span><span><FontAwesomeIcon icon={faGem} /> Premium comfort</span></div></div><div className="hero-side-card"><div className="hero-side-card__media" style={{ backgroundImage: `url(${media.makkah})` }}><div className="hero-video-placeholder"><FontAwesomeIcon icon={faCirclePlay} /><span>Licensed Makkah video<br /><small>Add your licensed content here</small></span></div></div><div className="hero-side-card__caption"><span>01 / 04</span><strong>A quieter way to travel</strong><span>Saudi Arabia</span></div></div></div>
    <div className="hero-orbit hero-orbit--one" /><div className="hero-orbit hero-orbit--two" />
  </section>;
}

export function Ticker() { return <div className="ticker"><div className="ticker-track">{[...tickerItems, ...tickerItems].map((item, index) => <span key={`${item}-${index}`}><i />{item}</span>)}</div></div>; }

export function ServiceCard({ service }: { service: Service }) { return <article className="service-card"><div className="service-card__image" style={{ backgroundImage: `linear-gradient(180deg, transparent 15%, rgba(0,0,0,.78)), url(${service.image})` }}><div className="service-icon"><FontAwesomeIcon icon={iconMap[service.icon]} /></div><span className="service-card__eyebrow">{service.eyebrow}</span></div><div className="service-card__body"><h3>{service.title}</h3><p>{service.description}</p><div className="service-card__actions"><Link className="text-link" href={`/services/${service.slug}`}>View details <FontAwesomeIcon icon={faArrowRight} /></Link><button className="mini-book" onClick={openBooking}>Book <FontAwesomeIcon icon={faArrowRight} /></button></div></div></article>; }

export function VehicleCard({ vehicle }: { vehicle: Vehicle }) { return <article className="vehicle-card"><Link href={`/fleet/${vehicle.slug}`} className="vehicle-card__image" style={{ backgroundImage: `linear-gradient(180deg, transparent 30%, rgba(0,0,0,.78)), url(${vehicle.image})` }}><span className="vehicle-category">{vehicle.category}</span><span className="vehicle-arrow"><FontAwesomeIcon icon={faArrowRight} /></span></Link><div className="vehicle-card__body"><Link href={`/fleet/${vehicle.slug}`}><h3>{vehicle.name}</h3></Link><p>{vehicle.intro}</p><div className="vehicle-card__footer"><span><FontAwesomeIcon icon={faCarSide} /> Private travel</span><button className="mini-book" onClick={openBooking}>Book <FontAwesomeIcon icon={faArrowRight} /></button></div></div></article>; }

export function ReelStrip() { return <div className="reel-strip">{reels.map((reel, index) => <article className="reel-card" key={reel.title} style={{ backgroundImage: `linear-gradient(180deg, transparent 36%, rgba(0,0,0,.85)), url(${reel.image})` }}><span className="reel-number">0{index + 1}</span><div><span>{reel.label}</span><h3>{reel.title}</h3><span className="reel-play"><FontAwesomeIcon icon={faCirclePlay} /> Add your Instagram Reel here</span></div></article>)}</div>; }

export function ExperienceBand() { return <section className="experience-band"><div className="experience-band__image" style={{ backgroundImage: `url(${media.desert})` }} /><div className="experience-band__content"><span className="eyebrow eyebrow--gold">More than a transfer</span><h2>For the route,<br /><em>and the reason.</em></h2><p>When the journey matters, the small things matter too: a clear arrival plan, a comfortable vehicle, and a team that knows where you are going next.</p><Link className="gold-button" href="/about">Meet Manar Transport <FontAwesomeIcon icon={faArrowRight} /></Link></div></section>; }

export function ImpactStats() { return <div className="impact-stats"><div><strong>01</strong><span>Clear booking flow</span><p>Start with a short brief and continue in WhatsApp.</p></div><div><strong>02</strong><span>Considered routes</span><p>Airport, city, intercity, and pilgrimage travel planning.</p></div><div><strong>03</strong><span>Human follow-up</span><p>Availability and final trip details are confirmed by the team.</p></div></div>; }

export function PromiseList() { return <div className="promise-list"><div><FontAwesomeIcon icon={faShieldHalved} /><span><strong>Comfort without complication</strong><small>A more composed experience from the first message to the final drop-off.</small></span></div><div><FontAwesomeIcon icon={faHeadset} /><span><strong>Support when it counts</strong><small>WhatsApp-first coordination keeps details in one simple place.</small></span></div><div><FontAwesomeIcon icon={faSuitcaseRolling} /><span><strong>Made for real travel</strong><small>Thoughtful options for luggage, family groups, and longer journeys.</small></span></div></div>; }
