import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faEnvelope, faLocationDot, faMessage, faPhone } from "@fortawesome/free-solid-svg-icons";
import { useEffect } from "react";
import { Link } from "wouter";
import { PageIntro } from "@/pages/PageBlocks";
import { contact, media } from "@/data/siteData";
import { openBooking } from "@/components/booking/BookingModal";
import { buildWhatsAppContactUrl } from "@/utils/whatsapp";
import { setPageMetadata } from "@/utils/metadata";

export default function ContactPage() { useEffect(() => setPageMetadata("Contact Manar Transport", "Contact Manar Transport by WhatsApp, email, or direct booking request."), []); return <div><PageIntro eyebrow="Contact" title="Let’s start with a conversation." body="Share a few details and the Manar Transport team can follow up with availability, route planning, and next steps." image={media.chauffeur} /><section className="section container contact-grid"><div className="contact-copy"><span className="eyebrow">Reach the team</span><h2>Your next journey<br /><em>starts here.</em></h2><p>For the fastest response, use WhatsApp. For a structured request, open the booking form and send the pre-filled message directly to the team.</p><div className="contact-details"><a href={buildWhatsAppContactUrl()} target="_blank" rel="noreferrer"><FontAwesomeIcon icon={faMessage} /><span><small>WhatsApp</small><strong>{contact.whatsapp}</strong></span></a><a href={`mailto:${contact.email}`}><FontAwesomeIcon icon={faEnvelope} /><span><small>Email</small><strong>{contact.email}</strong></span></a><div><FontAwesomeIcon icon={faLocationDot} /><span><small>Address</small><strong>{contact.address}</strong></span></div><div><FontAwesomeIcon icon={faPhone} /><span><small>Business hours</small><strong>[ADD BUSINESS HOURS]</strong></span></div></div></div><div className="contact-card"><span className="eyebrow eyebrow--gold">Booking flow</span><h3>Keep it simple.</h3><ol><li><b>01</b> Tell us your name and contact details.</li><li><b>02</b> Add your travel date and trip details.</li><li><b>03</b> Review the WhatsApp message before sending.</li></ol><button className="gold-button gold-button--full" onClick={openBooking}><FontAwesomeIcon icon={faMessage} /> Open booking form</button><p className="form-note">Your details are not stored by this static site. The request opens in WhatsApp for you to send.</p></div></section><section className="section section--soft"><div className="container map-placeholder"><span className="eyebrow">Location placeholder</span><h2>24 B, Islamabad,<br /><em>Sector F-14.</em></h2><p>A map embed can be added here once the final business location and map preference are confirmed.</p><Link className="text-link" href={buildWhatsAppContactUrl("Hello Manar Transport, I would like to confirm your location.")} target="_blank">Ask on WhatsApp <FontAwesomeIcon icon={faMessage} /></Link></div></section></div>; }
