import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowRight, faMagnifyingGlass } from "@fortawesome/free-solid-svg-icons";
import { useEffect, useMemo, useState } from "react";
import { Link, useLocation } from "wouter";
import { services, vehicles } from "@/data/siteData";
import { setPageMetadata } from "@/utils/metadata";

const pages = [{ title: "About Manar Transport", type: "About", href: "/about", body: "A considered approach to safe and comfortable Saudi-focused journeys." }, { title: "Travel Information", type: "Information", href: "/info", body: "Useful booking, airport, travel, and Hajj & Umrah information." }, { title: "Policies", type: "Policies", href: "/policies", body: "Terms, privacy, and refund policy placeholders for final legal review." }];

export default function SearchPage() { const [location, navigate] = useLocation(); const initial = new URLSearchParams(location.split("?")[1] || "").get("q") || ""; const [query, setQuery] = useState(initial); useEffect(() => { setPageMetadata("Search", "Search Manar Transport services, fleet, information, and company pages."); }, []); const results = useMemo(() => { const needle = query.toLowerCase().trim(); if (!needle) return [...services.map((item) => ({ title: item.title, type: "Service", href: `/services/${item.slug}`, body: item.description })), ...vehicles.map((item) => ({ title: item.name, type: "Fleet", href: `/fleet/${item.slug}`, body: item.intro })), ...pages]; return [...services.map((item) => ({ title: item.title, type: "Service", href: `/services/${item.slug}`, body: item.description })), ...vehicles.map((item) => ({ title: item.name, type: "Fleet", href: `/fleet/${item.slug}`, body: item.intro })), ...pages].filter((item) => `${item.title} ${item.type} ${item.body}`.toLowerCase().includes(needle)); }, [query]); const submit = (event: React.FormEvent) => { event.preventDefault(); navigate(`/search${query ? `?q=${encodeURIComponent(query)}` : ""}`); }; return <div className="search-page container"><div className="search-page__head"><span className="eyebrow">Search</span><h1>Find your way<br /><em>through Manar.</em></h1><form onSubmit={submit} className="search-form search-form--page"><FontAwesomeIcon icon={faMagnifyingGlass} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search services, fleet, or information" /><button type="submit">Search</button></form></div><div className="search-results"><span className="eyebrow">{query ? `${results.length} results for “${query}”` : "Start with a page"}</span>{results.length ? results.map((item) => <Link className="search-result" href={item.href} key={`${item.type}-${item.title}`}><span>{item.type}</span><div><h3>{item.title}</h3><p>{item.body}</p></div><FontAwesomeIcon icon={faArrowRight} /></Link>) : <div className="empty-search"><h2>Nothing matched that search.</h2><p>Try “Makkah”, “fleet”, “airport”, or “about”.</p></div>}</div></div>; }
