import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowRight, faHandshake, faLock, faPercent } from "@fortawesome/free-solid-svg-icons";
import { useEffect } from "react";
import { Link } from "wouter";
import { PageIntro, BookingCTA } from "@/pages/PageBlocks";
import { media } from "@/data/siteData";
import { setPageMetadata } from "@/utils/metadata";

export function TravelAgentPage() { useEffect(() => { setPageMetadata("Travel Agent Partners", "Partner with Manar Transport for transportation planning and future agent workflows."); }, []); return <div><PageIntro eyebrow="Travel agent" title="Build a better handoff for your clients." body="A partner-facing space for agencies and travel planners. Final program terms and access flows should be added when confirmed." image={media.van} /><section className="section container partner-grid"><div className="partner-card"><FontAwesomeIcon icon={faHandshake} /><h3>Partner with us</h3><p>Start a conversation about connecting your clients with a calm, WhatsApp-first transportation experience.</p><Link className="text-link" href="/contact">Start a conversation <FontAwesomeIcon icon={faArrowRight} /></Link></div><div className="partner-card"><FontAwesomeIcon icon={faLock} /><h3>Partner login</h3><p>Access is intentionally not wired to fake authentication. The interface is ready for a future secure backend.</p><Link className="text-link" href="/travel-agent/partner-login">View login shell <FontAwesomeIcon icon={faArrowRight} /></Link></div><div className="partner-card"><FontAwesomeIcon icon={faPercent} /><h3>Commission program</h3><p>Learn how a future commission program can be presented without inventing percentages or commercial terms.</p><Link className="text-link" href="/travel-agent/commission-program">Explore program <FontAwesomeIcon icon={faArrowRight} /></Link></div></section><BookingCTA eyebrow="Partner conversations" title="Let’s make client travel feel simpler." /></div>; }

export function PartnerLoginPage() { useEffect(() => { setPageMetadata("Partner Login", "Partner login interface placeholder for Manar Transport."); }, []); return <div><PageIntro eyebrow="Travel agent / partner login" title="A secure doorway, ready for later." body="This is a front-end interface shell only. No credentials are stored and no fake authentication is implemented." image={media.chauffeur} /><section className="section container login-shell"><div className="login-card"><span className="eyebrow">Future access</span><h2>Partner sign in</h2><label>Email<input type="email" placeholder="partner@example.com" /></label><label>Password<input type="password" placeholder="••••••••" /></label><button className="gold-button gold-button--full" onClick={() => alert("Authentication will be connected when a secure backend is configured.")}>Continue <FontAwesomeIcon icon={faArrowRight} /></button><p>This UI is prepared for a future auth layer. Connect it to a secure backend before collecting partner credentials.</p></div></section></div>; }

export function CommissionPage() { useEffect(() => { setPageMetadata("Commission Program", "Manar Transport commission program placeholder."); }, []); return <div><PageIntro eyebrow="Travel agent / commission" title="A clearer way to partner." body="A professional structure for a future commission program, with no invented rates or commercial promises." image={media.desert} /><section className="section container commission-page"><div><span className="eyebrow">Program outline</span><h2>Built around transparency,<br /><em>not assumptions.</em></h2></div><div className="commission-steps"><div><b>01</b><h3>Partner onboarding</h3><p>[ADD COMPANY CONTENT] Explain who the program is for and what information a partner needs to provide.</p></div><div><b>02</b><h3>Booking handoff</h3><p>Define how an agency refers a client, how the booking is attributed, and how confirmation is shared.</p></div><div><b>03</b><h3>Commercial terms</h3><p>[ADD COMMISSION TERMS] Add the approved rates, payment timing, exclusions, and support process.</p></div></div></section><BookingCTA /></div>; }
