import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowRight, faBookOpen, faCircleInfo, faPlaneArrival, faRoute } from "@fortawesome/free-solid-svg-icons";
import { useEffect } from "react";
import { Link } from "wouter";
import { PageIntro, BookingCTA } from "@/pages/PageBlocks";
import { SectionHeading } from "@/components/ui/BrandPrimitives";
import { faqs, media } from "@/data/siteData";
import { setPageMetadata } from "@/utils/metadata";

export default function InfoPage() { useEffect(() => { setPageMetadata("Travel Information", "Useful booking, airport, travel, and Hajj & Umrah information for Manar Transport customers."); }, []); return <div><PageIntro eyebrow="Information" title="A little more clarity before you go." body="Useful guidance for planning your transportation. Current religious, regulatory, and travel requirements should always be confirmed with official authorities." image={media.makkah} /><section className="section container"><SectionHeading eyebrow="Useful information" title="The practical things, in one place." body="These cards are structured for approved company guidance and links to official sources as they are confirmed." /><div className="info-grid"><div><FontAwesomeIcon icon={faPlaneArrival} /><h3>Airport information</h3><p>Allow room for arrival formalities, baggage collection, and the meet-and-greet plan.</p><Link className="text-link" href="/contact">Ask the team <FontAwesomeIcon icon={faArrowRight} /></Link></div><div><FontAwesomeIcon icon={faRoute} /><h3>Travel information</h3><p>Share your route, date, group size, and any timing considerations in the booking message.</p><Link className="text-link" href="/services">Explore services <FontAwesomeIcon icon={faArrowRight} /></Link></div><div><FontAwesomeIcon icon={faBookOpen} /><h3>Hajj &amp; Umrah</h3><p>For current official guidance and religious questions, consult Saudi authorities and qualified religious authorities.</p><Link className="text-link" href="https://www.visitsaudi.com/" target="_blank">Official travel source <FontAwesomeIcon icon={faArrowRight} /></Link></div><div><FontAwesomeIcon icon={faCircleInfo} /><h3>Booking information</h3><p>Your message opens in WhatsApp. Staff follow up there with availability and final details; no fake CRM is used.</p><Link className="text-link" href="/contact">Start a request <FontAwesomeIcon icon={faArrowRight} /></Link></div></div></section><section className="section section--soft container info-faq"><div><span className="eyebrow">Frequently asked</span><h2>Good questions<br /><em>make good journeys.</em></h2></div><div className="faq-list">{faqs.map((faq) => <details key={faq.question}><summary>{faq.question}<span>+</span></summary><p>{faq.answer}</p></details>)}</div></section><BookingCTA /></div>; }
